name: Sync to Gitee

on:
  release:
    types: [published]

jobs:
  sync-to-gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync to Gitee
        run: |
          git remote add gitee https://drsanwujiang:${{ secrets.GITEE_TOKEN }}@gitee.com/drsanwujiang/DiceRobot.git
          git push --force --all gitee
          git push --force --tags gitee