name: Sync to Gitee

on:
  release:
    types: [published]

jobs:
  sync-to-gitee:
    name: Sync repository to Gitee
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync to Gitee
        uses: abersheeran/sync-gitee-mirror@v1-beta
        with:
          repository: abersheeran/sync-gitee-mirror
          username: drsanwujiang
          password: ${{ secrets.GITEE_TOKEN }}