name: Upload to S3

on:
  release:
    types: [published]

jobs:
  upload-to-s3:
    name: Upload source code to S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compress source code
        run: |
          zip -r dicerobot-${{ github.ref_name }}.zip . -x ".git/*"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: |
          aws s3 cp dicerobot-${{ github.ref_name }}.zip s3://${{ secrets.AWS_BUCKET }}/dicerobot/